import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/Home/Navigation/Topbar/Topbar";
import Navigation from "@/Home/Navigation/Mainbar/Navigation";
import Footer from "@/Home/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "vosostore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Topbar/>
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
